# AI团队系统知识库配置

# 开发工程师文档
developer_docs:
  - title: "Python官方文档"
    url: "https://docs.python.org/zh-cn/3/"
    description: "Python官方中文文档，包含语言特性和标准库"
    
  - title: "Python编码规范 (PEP 8)"
    url: "https://peps.python.org/pep-0008/"
    description: "Python代码风格指南"
    
  - title: "FastAPI官方文档"
    url: "https://fastapi.tiangolo.com/zh/"
    description: "现代、快速的Web框架文档"
    
  - title: "React官方文档"
    url: "https://zh-hans.react.dev/"
    description: "React中文官方文档"
    
  - title: "TypeScript官方文档"
    url: "https://www.typescriptlang.org/zh/docs/"
    description: "TypeScript官方中文文档"
    
  - title: "Docker官方文档"
    url: "https://docs.docker.com/get-started/"
    description: "Docker容器化技术文档"
    
  - title: "PostgreSQL官方文档"
    url: "https://www.postgresql.org/docs/current/"
    description: "PostgreSQL数据库官方文档"
    
  - title: "Git官方文档"
    url: "https://git-scm.com/doc"
    description: "Git版本控制工具文档"

# AI/ML工程师文档
ai_ml_docs:
  - title: "OpenAI API文档"
    url: "https://platform.openai.com/docs"
    description: "OpenAI API官方文档"
    
  - title: "LangChain文档"
    url: "https://python.langchain.com/docs/get_started/introduction"
    description: "LangChain LLM应用开发框架"
    
  - title: "AutoGen文档"
    url: "https://microsoft.github.io/autogen/"
    description: "微软AutoGen多Agent协作框架"
    
  - title: "CrewAI文档"
    url: "https://docs.crewai.com/"
    description: "CrewAI任务驱动的Agent框架"
    
  - title: "Hugging Face文档"
    url: "https://huggingface.co/docs"
    description: "Hugging Face模型和工具文档"
    
  - title: "PyTorch官方文档"
    url: "https://pytorch.org/docs/stable/index.html"
    description: "PyTorch深度学习框架文档"
    
  - title: "TensorFlow官方文档"
    url: "https://www.tensorflow.org/guide"
    description: "TensorFlow机器学习框架文档"

# 产品经理学习资源
pm_resources:
  - title: "产品经理入门指南"
    url: "https://www.zhihu.com/question/19551592"
    description: "知乎产品经理入门话题"
    
  - title: "需求分析方法论"
    url: "https://www.woshipm.com/pmd/1234567.html"
    description: "产品经理需求分析实战指南"
    
  - title: "用户研究方法"
    url: "https://www.nngroup.com/articles/user-research/"
    description: "Nielsen Norman Group用户研究指南"
    
  - title: "产品设计思维"
    url: "https://www.interaction-design.org/literature/topics/design-thinking"
    description: "交互设计基金会设计思维指南"
    
  - title: "敏捷开发Scrum指南"
    url: "https://scrumguides.org/scrum-guide.html"
    description: "Scrum官方指南"
    
  - title: "用户体验设计原则"
    url: "https://www.nngroup.com/articles/ten-usability-heuristics/"
    description: "尼尔森十大可用性启发式原则"

# 测试工程师资源
qa_resources:
  - title: "Selenium官方文档"
    url: "https://selenium-python.readthedocs.io/"
    description: "Selenium自动化测试框架"
    
  - title: "Pytest官方文档"
    url: "https://docs.pytest.org/en/stable/"
    description: "Python测试框架Pytest"
    
  - title: "Postman学习中心"
    url: "https://learning.postman.com/"
    description: "API测试工具Postman学习资源"
    
  - title: "测试驱动开发(TDD)"
    url: "https://martinfowler.com/bliki/TestDrivenDevelopment.html"
    description: "Martin Fowler的TDD介绍"
    
  - title: "性能测试指南"
    url: "https://k6.io/docs/"
    description: "k6性能测试工具文档"

# DevOps工程师资源
devops_resources:
  - title: "Kubernetes官方文档"
    url: "https://kubernetes.io/zh/docs/"
    description: "Kubernetes容器编排平台文档"
    
  - title: "Jenkins官方文档"
    url: "https://www.jenkins.io/doc/"
    description: "Jenkins CI/CD工具文档"
    
  - title: "Prometheus监控文档"
    url: "https://prometheus.io/docs/"
    description: "Prometheus监控系统文档"
    
  - title: "Grafana官方文档"
    url: "https://grafana.com/docs/"
    description: "Grafana数据可视化平台"
    
  - title: "Terraform官方文档"
    url: "https://www.terraform.io/docs"
    description: "Terraform基础设施即代码工具"

# 前端开发资源
frontend_resources:
  - title: "MDN Web文档"
    url: "https://developer.mozilla.org/zh-CN/"
    description: "Mozilla开发者网络Web技术文档"
    
  - title: "CSS参考手册"
    url: "https://developer.mozilla.org/zh-CN/docs/Web/CSS/Reference"
    description: "CSS完整参考文档"
    
  - title: "JavaScript参考"
    url: "https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference"
    description: "JavaScript完整参考文档"
    
  - title: "Vue.js官方文档"
    url: "https://cn.vuejs.org/"
    description: "Vue.js渐进式JavaScript框架"
    
  - title: "Tailwind CSS文档"
    url: "https://tailwindcss.com/docs"
    description: "Tailwind CSS实用优先的CSS框架"

# 后端开发资源
backend_resources:
  - title: "Django官方文档"
    url: "https://docs.djangoproject.com/zh-hans/4.2/"
    description: "Django Web框架官方文档"
    
  - title: "Flask官方文档"
    url: "https://flask.palletsprojects.com/"
    description: "Flask轻量级Web框架"
    
  - title: "SQLAlchemy文档"
    url: "https://docs.sqlalchemy.org/"
    description: "SQLAlchemy Python SQL工具包"
    
  - title: "Redis官方文档"
    url: "https://redis.io/docs/"
    description: "Redis内存数据库文档"
    
  - title: "Celery官方文档"
    url: "https://docs.celeryq.dev/"
    description: "Celery分布式任务队列"

# 项目管理资源
project_management:
  - title: "敏捷开发宣言"
    url: "https://agilemanifesto.org/iso/zhchs/"
    description: "敏捷软件开发宣言"
    
  - title: "Scrum指南"
    url: "https://scrumguides.org/scrum-guide.html"
    description: "Scrum官方指南"
    
  - title: "看板方法"
    url: "https://kanbanize.com/kanban-resources/getting-started/what-is-kanban"
    description: "看板项目管理方法介绍"
    
  - title: "项目管理知识体系(PMBOK)"
    url: "https://www.pmi.org/pmbok-guide-standards"
    description: "PMI项目管理标准"

# 设计资源
design_resources:
  - title: "Figma官方文档"
    url: "https://help.figma.com/"
    description: "Figma设计工具官方帮助"
    
  - title: "Material Design指南"
    url: "https://m3.material.io/"
    description: "Google Material Design设计系统"
    
  - title: "Apple人机界面指南"
    url: "https://developer.apple.com/design/human-interface-guidelines/"
    description: "Apple设计指南"
    
  - title: "色彩理论"
    url: "https://www.interaction-design.org/literature/topics/color-theory"
    description: "交互设计色彩理论"

# 数据科学资源
data_science:
  - title: "Pandas官方文档"
    url: "https://pandas.pydata.org/docs/"
    description: "Pandas数据分析库"
    
  - title: "NumPy官方文档"
    url: "https://numpy.org/doc/"
    description: "NumPy数值计算库"
    
  - title: "Matplotlib官方文档"
    url: "https://matplotlib.org/stable/contents.html"
    description: "Matplotlib数据可视化库"
    
  - title: "Scikit-learn官方文档"
    url: "https://scikit-learn.org/stable/"
    description: "Scikit-learn机器学习库"
    
  - title: "Jupyter官方文档"
    url: "https://jupyter.org/documentation"
    description: "Jupyter交互式计算环境"

# 安全资源
security_resources:
  - title: "OWASP Top 10"
    url: "https://owasp.org/www-project-top-ten/"
    description: "OWASP十大Web应用安全风险"
    
  - title: "Web安全测试指南"
    url: "https://owasp.org/www-project-web-security-testing-guide/"
    description: "OWASP Web安全测试指南"
    
  - title: "密码学基础"
    url: "https://cryptography.io/en/latest/"
    description: "Python密码学库文档"

# 最佳实践
best_practices:
  - title: "Google Python风格指南"
    url: "https://google.github.io/styleguide/pyguide.html"
    description: "Google Python代码风格指南"
    
  - title: "Airbnb JavaScript风格指南"
    url: "https://github.com/airbnb/javascript"
    description: "Airbnb JavaScript代码规范"
    
  - title: "Git提交信息规范"
    url: "https://www.conventionalcommits.org/zh-hans/"
    description: "约定式提交规范"
    
  - title: "RESTful API设计指南"
    url: "https://restfulapi.net/"
    description: "RESTful API设计最佳实践" 